# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moranTest <- function(xr, Wr, reps) {
    .Call('phylosignal_moranTest', PACKAGE = 'phylosignal', xr, Wr, reps)
}

kTest <- function(xr, vcvr, reps) {
    .Call('phylosignal_kTest', PACKAGE = 'phylosignal', xr, vcvr, reps)
}

kStarTest <- function(xr, vcvr, reps) {
    .Call('phylosignal_kStarTest', PACKAGE = 'phylosignal', xr, vcvr, reps)
}

pagelLogLik <- function(lambda, xr, vcvr) {
    .Call('phylosignal_pagelLogLik', PACKAGE = 'phylosignal', lambda, xr, vcvr)
}

